name = "ghostnet-site"
compatibility_date = "2024-08-28"

[env.production]
routes = [
  { pattern = "cyborgjedi.com/*", zone_name = "cyborgjedi.com" },
  { pattern = "www.cyborgjedi.com/*", zone_name = "cyborgjedi.com" }
]

# Static site configuration
[site]
bucket = "./"
entry-point = "index.html"
